### ISSUE TITLE
Create "bot beer me" functionality

### ISSUE THREAD

**Issue by hitjim** [devict/devict-hubot#1]
bot watches for "bot beer me XYZ" and returns a ratebeer review or some other relevant info for a particular beer XYZ.

**Comment by hitjim** [comment]
Hmmm... You mean hitjim hasn't worked on this yet???

**Comment by hitjim** [comment]
I'm looking at this as of last night.  brewerydb looks like a ghost town.  Ratebeer has an API which shows promise.

**Comment by benblankley** [comment]
This one can probably be closed now.
