### ISSUE TITLE
bot help should reply in a direct message

### ISSUE THREAD

**Issue by benblankley** [devict/devict-hubot#25]
Maybe some hints here:
https://github.com/slackhq/hubot-slack/issues/159

Replace the repository version of help.coffee
https://github.com/hubot-scripts/hubot-help/blob/master/src/help.coffee

with a modified one for us.

Would this work?

change
69     msg.send emit 
to
69     robot.send {room: message.envelope.user.name}, emit

**Comment by MrsJaw** [comment]
That was pretty much it yeah! Thanks! 
    robot.send { room: msg.message.user.name }, emit

**Comment by benblankley** [comment]
I'm going to close this one, because the patch is incoming soon! :dancer:
