### ISSUE TITLE
Events: Make an Image of Text Instead of Text

### ISSUE THREAD

**Issue by jcbwlkr** [devict/devict-hubot#42]
See images for description

<img width="806" alt="screen shot 2016-10-20 at 1 53 27 pm" src="https://cloud.githubusercontent.com/assets/2027263/19573637/b6dc0c38-96cc-11e6-992d-c8ce07f991ed.png">
<img width="987" alt="screen shot 2016-10-20 at 1 53 48 pm" src="https://cloud.githubusercontent.com/assets/2027263/19573644/bcfbb37a-96cc-11e6-93c5-745ccc6a8587.png">

We deploy to Heroku so whatever solution we come up with would need to work there.

**Comment by imacrayon** [comment]
What if the events were included as a message attachment? [Here's an example](https://api.slack.com/docs/messages/builder?msg=%7B%22text%22%3A%22WWC%20%3D%20Women%20Who%20Code%2C%20OW%20%3D%20Open%20Wichita%22%2C%22attachments%22%3A%5B%7B%22fields%22%3A%5B%7B%22title%22%3A%22%E2%98%95%20Code%20%26%20Coffee%22%2C%22value%22%3A%22Thu%2012%2F22%2007%3A00am%20%40%20The%20Labor%20Party%5CndevICT%22%2C%22short%22%3Atrue%7D%2C%7B%22title%22%3A%22Maker%20Mondays%22%2C%22value%22%3A%22Mon%2012%2F26%2007%3A00pm%20%40%20MakeICT%20Makerspace%5CnMakeICT%22%2C%22short%22%3Atrue%7D%2C%7B%22title%22%3A%22%E2%87%AA%20Study%20Hall%22%2C%22value%22%3A%22Mon%2012%2F26%2007%3A00pm%20%40%20The%20Labor%20Party%5CnWWC%2FdevICT%22%2C%22short%22%3Atrue%7D%2C%7B%22title%22%3A%22Woodshop%20Safety%20Class%22%2C%22value%22%3A%22Wed%2012%2F28%2012%3A00pm%20%40%20MakeICT%20Makerspace%5CnMakeICT%22%2C%22short%22%3Atrue%7D%2C%7B%22title%22%3A%22%E2%98%95%20Code%20%26%20Coffee%22%2C%22value%22%3A%22Thu%2012%2F29%2007%3A00am%20%40%20The%20Labor%20Party%5CndevICT%22%2C%22short%22%3Atrue%7D%2C%7B%22title%22%3A%22%E2%87%AA%20Study%20Hall%22%2C%22value%22%3A%22Mon%2001%2F02%2007%3A00pm%20%40%20The%20Labor%20Party%5CnWWC%2FdevICT%22%2C%22short%22%3Atrue%7D%2C%7B%22title%22%3A%22Virtual%20Hack%20Night%22%2C%22value%22%3A%22Wed%2001%2F04%2008%3A00pm%20%40%20Open%20Wichita%20Slack%5Cn%22%2C%22short%22%3Atrue%7D%2C%7B%22title%22%3A%22%E2%98%95%20Code%20%26%20Coffee%22%2C%22value%22%3A%22Thu%2001%2F05%2007%3A00am%20%40%20The%20Labor%20Party%5CndevICT%22%2C%22short%22%3Atrue%7D%2C%7B%22title%22%3A%22Women%20Who%20Code%20Lunch%22%2C%22value%22%3A%22Thu%2001%2F05%2011%3A30am%20%40%20%5CnWWC%22%2C%22short%22%3Atrue%7D%2C%7B%22title%22%3A%22%E2%87%AA%20Study%20Hall%22%2C%22value%22%3A%22Mon%2001%2F09%2007%3A00pm%20%40%20The%20Labor%20Party%5CnWWC%22%2C%22short%22%3Atrue%7D%2C%7B%22title%22%3A%22Maker%20Mondays%22%2C%22value%22%3A%22Mon%2001%2F09%2007%3A00pm%20%40%20MakeICT%20Makerspace%5CnMakeICT%22%2C%22short%22%3Atrue%7D%2C%7B%22title%22%3A%22%E2%87%AA%20Study%20Hall%22%2C%22value%22%3A%22Mon%2001%2F09%2007%3A00pm%20%40%20The%20Labor%20Party%5CndevICT%22%2C%22short%22%3Atrue%7D%2C%7B%22title%22%3A%22Hangout%22%2C%22value%22%3A%22Tue%2001%2F10%2006%3A00pm%20%40%20The%20Labor%20Party%5CndevICT%22%2C%22short%22%3Atrue%7D%2C%7B%22title%22%3A%22Virtual%20Hack%20Night%22%2C%22value%22%3A%22Wed%2001%2F11%2008%3A00pm%20%40%20Open%20Wichita%20Slack%5CnOW%22%2C%22short%22%3Atrue%7D%2C%7B%22title%22%3A%22%E2%98%95%20Code%20%26%20Coffee%22%2C%22value%22%3A%22Thu%2001%2F12%2007%3A00am%20%40%20The%20Labor%20Party%5CndevICT%22%2C%22short%22%3Atrue%7D%2C%7B%22title%22%3A%22Laser%20Cutter%20Authori..%22%2C%22value%22%3A%22Thu%2001%2F12%2006%3A00pm%20%40%20MakeICT%20Makerspace%5CnMakeICT%22%2C%22short%22%3Atrue%7D%2C%7B%22title%22%3A%22%E2%87%AA%20Study%20Hall%22%2C%22value%22%3A%22Mon%2001%2F16%2007%3A00pm%20%40%20The%20Labor%20Party%5CnWWC%2FdevICT%22%2C%22short%22%3Atrue%7D%2C%7B%22title%22%3A%22Virtual%20Hack%20Night%22%2C%22value%22%3A%22Wed%2001%2F18%2008%3A00pm%20%40%20Open%20Wichita%20Slack%5CnOW%22%2C%22short%22%3Atrue%7D%2C%7B%22title%22%3A%22%E2%98%95%20Code%20%26%20Coffee%22%2C%22value%22%3A%22Thu%2001%2F19%2007%3A00am%20%40%20The%20Labor%20Party%5CndevICT%22%2C%22short%22%3Atrue%7D%2C%7B%22title%22%3A%22%E2%99%AF%20.NET%20Night%22%2C%22value%22%3A%22Thu%2001%2F19%2007%3A00pm%20%40%20The%20Labor%20Party%5CndevICT%22%2C%22short%22%3Atrue%7D%2C%7B%22title%22%3A%22WWC%20Movie%20Night%20-%20Hi..%22%2C%22value%22%3A%22Fri%2001%2F20%2008%3A00pm%20%40%20Warren%20Theater%20-%20WEST%5CnWWC%22%2C%22short%22%3Atrue%7D%2C%7B%22title%22%3A%22%E2%87%AA%20Study%20Hall%22%2C%22value%22%3A%22Mon%2001%2F23%2007%3A00pm%20%40%20The%20Labor%20Party%5CndevICT%22%2C%22short%22%3Atrue%7D%2C%7B%22title%22%3A%22Maker%20Mondays%22%2C%22value%22%3A%22Mon%2001%2F23%2007%3A00pm%20%40%20MakeICT%20Makerspace%5CnMakeICT%22%2C%22short%22%3Atrue%7D%2C%7B%22title%22%3A%22%E2%87%AA%20Study%20Hall%22%2C%22value%22%3A%22Mon%2001%2F23%2007%3A00pm%20%40%20The%20Labor%20Party%5CnWWC%22%2C%22short%22%3Atrue%7D%2C%7B%22title%22%3A%22Virtual%20Hack%20Night%22%2C%22value%22%3A%22Wed%2001%2F25%2008%3A00pm%20%40%20Open%20Wichita%20Slack%5CnOW%22%2C%22short%22%3Atrue%7D%2C%7B%22title%22%3A%22%E2%98%95%20Code%20%26%20Coffee%22%2C%22value%22%3A%22Thu%2001%2F26%2007%3A00am%20%40%20The%20Labor%20Party%5CndevICT%22%2C%22short%22%3Atrue%7D%2C%7B%22title%22%3A%22%E2%87%AA%20Study%20Hall%22%2C%22value%22%3A%22Mon%2001%2F30%2007%3A00pm%20%40%20The%20Labor%20Party%5CndevICT%2FWWC%2C%22%2C%22short%22%3Atrue%7D%2C%7B%22title%22%3A%22Virtual%20Hack%20Night%22%2C%22value%22%3A%22Wed%2002%2F01%2008%3A00pm%20%40%20Open%20Wichita%20Slack%5CnOW%22%2C%22short%22%3Atrue%7D%2C%7B%22title%22%3A%22%E2%98%95%20Code%20%26%20Coffee%22%2C%22value%22%3A%22Thu%2002%2F02%2007%3A00am%20%40%20The%20Labor%20Party%5CndevICT%22%2C%22short%22%3Atrue%7D%2C%7B%22title%22%3A%22Women%20Who%20Code%20Lunch%22%2C%22value%22%3A%22Thu%2002%2F02%2011%3A30am%20%40%20%5CnWWC%22%2C%22short%22%3Atrue%7D%2C%7B%22title%22%3A%22%E2%87%AA%20Study%20Hall%22%2C%22value%22%3A%22Mon%2002%2F06%2007%3A00pm%20%40%20The%20Labor%20Party%5CndevICT%22%2C%22short%22%3Atrue%7D%2C%7B%22title%22%3A%22Maker%20Mondays%22%2C%22value%22%3A%22Mon%2002%2F06%2007%3A00pm%20%40%20MakeICT%20Makerspace%5CnMakeICT%22%2C%22short%22%3Atrue%7D%2C%7B%22title%22%3A%22%E2%87%AA%20Study%20Hall%22%2C%22value%22%3A%22Mon%2002%2F06%2007%3A00pm%20%40%20The%20Labor%20Party%5CnWWC%22%2C%22short%22%3Atrue%7D%2C%7B%22title%22%3A%22Virtual%20Hack%20Night%22%2C%22value%22%3A%22Wed%2002%2F08%2008%3A00pm%20%40%20Open%20Wichita%20Slack%5CnOW%22%2C%22short%22%3Atrue%7D%2C%7B%22title%22%3A%22%E2%98%95%20Code%20%26%20Coffee%22%2C%22value%22%3A%22Thu%2002%2F09%2007%3A00am%20%40%20The%20Labor%20Party%5CndevICT%22%2C%22short%22%3Atrue%7D%2C%7B%22title%22%3A%22%E2%87%AA%20Study%20Hall%22%2C%22value%22%3A%22Mon%2002%2F13%2007%3A00pm%20%40%20The%20Labor%20Party%5Cn%22%2C%22short%22%3Atrue%7D%2C%7B%22title%22%3A%22Hangout%22%2C%22value%22%3A%22Tue%2002%2F14%2006%3A00pm%20%40%20The%20Labor%20Party%5CndevICT%22%2C%22short%22%3Atrue%7D%2C%7B%22title%22%3A%22Virtual%20Hack%20Night%22%2C%22value%22%3A%22Wed%2002%2F15%2008%3A00pm%20%40%20Open%20Wichita%20Slack%5CnOW%22%2C%22short%22%3Atrue%7D%2C%7B%22title%22%3A%22%E2%98%95%20Code%20%26%20Coffee%22%2C%22value%22%3A%22Thu%2002%2F16%2007%3A00am%20%40%20The%20Labor%20Party%5CndevICT%22%2C%22short%22%3Atrue%7D%2C%7B%22title%22%3A%22%E2%87%AA%20Study%20Hall%22%2C%22value%22%3A%22Mon%2002%2F20%2007%3A00pm%20%40%20The%20Labor%20Party%5CnWWC%22%2C%22short%22%3Atrue%7D%2C%7B%22title%22%3A%22Maker%20Mondays%22%2C%22value%22%3A%22Mon%2002%2F20%2007%3A00pm%20%40%20MakeICT%20Makerspace%5CnMakeICT%22%2C%22short%22%3Atrue%7D%5D%7D%5D%7D).

**Comment by jcbwlkr** [comment]
Issue no longer necessary.
