### ISSUE TITLE
Make responses.js send reactions instead of image links

### ISSUE THREAD

**Issue by jcbwlkr** [devict/devict-hubot#43]
Many people feel that the images coming from responses.js are too invasive. This issue is to convert all of those images into emojis and have the bot "react" to certain messages.

Make an emoji reaction for each of these triggers
- `so good` => Franco
- `you're welcome` => Abed (one for the whole regex)
- `look at this` => One of the "look at that guy" pics
- `look at that` => Another one
- `look at it` => Another one

It _might_ be enough to have the bot do `msg.send('+:look_at_this:')` but that could lead to a race condition of the bot reacting to the wrong message. It's not the end of the world if that happens but if there's a better way to specifically react to the triggering message then let's do that.

**Comment by hitjim** [comment]
I might try that approach first and we'll see if the race condition is an issue after using it for a while.

**Comment by hitjim** [comment]
Shoot.  Forgot `you're welcome` in my PR
