### ISSUE TITLE
plus-plus doesn't level up unames that contain hyphens

### ISSUE THREAD

**Issue by hitjim** [devict/devict-hubot#5]
Case in point:

```
james-seymour++ for being a soothsayer
```
... results in the bot willfully ignoring james-seymour and thus tearing our family apart.

**Comment by MrsJaw** [comment]
Did this get fixed? Was it actually the problem to begin with?

![botpointswithhyphens](https://cloud.githubusercontent.com/assets/6324914/13683861/b556dd10-e6ce-11e5-8185-06206e53a955.png)

**Comment by MrsJaw** [comment]
Ahhhhhh ok
